### ISSUE TITLE
Alpha seed implementation (New Feature)

### ISSUE THREAD

**Issue by avive** [spacemeshos/cosmic#2]
## Intro
We are looking for a savvy and experienced front-end Typescript developer to tackle this funded issue. 
Please only apply if you believe you can provide a high-quality delivery that satisfies all the requirements outlined in this issue. Feel free to ask any questions about this issue in the conversation module on https://github.com/spacemeshos/cosmic/issues/2 - thanks for your contribution!

## Story
App developers who need to ship their apps across all major platforms will use this seed as the base of their app's codebase because it will save them lots of time and effort writing boilerplate code to support these platforms with one codebase without having any duplicated app logic and UI code.

## Requirements
- Implement the seed using the architecture and frameworks described in the readme.
- Please review the readme.md for an architectural overview of the different app components and modules and design the folder and project structure so it corresponds to the conceptual architecture modules
- The seed should be buildable and runnable on all platforms - iOS, Android, Web and Desktop via Electron.
- Please review the relevant projects in the wiki. For example - this is a working barebones seed for [react-native-web typescript](https://github.com/ethanneff/react-native-web-typescript)
- We are expecting clean, well documented and polished Typescript code.

## Demo App
- Running the seed should launch a simple demo app
- Demo App should have 2 screens with content
  - `Use case 1 - Basic navigation` - Clicking a button on the first screen should access the second screen. Clicking the button on the second screen should display the first screen
  - `User case 2 - User Interaction` - The first screen should also include a text input box accepting user provided text and a submit button . Submitting the text should display it in a label below the text box. All this functionality should be implemented using Redux for state modifications and UI updates based on state changes

## Testing
- Use [Jest testing suite](https://jestjs.io/)
- There should be unit tests and integration tests for all implemented functionality
- There must be a test that validates proper demo app startup on each supported platform. e.g display of first content screen without any errors

## Documentation & Coding Style

- All methods, models, types and interfaces *must be* documented via short and simple text comments
- Write basic docs in readme.md that include instructions for setting up the dev env, building, testing and running the seed on all targets
- Integrate `tslint` into the build workflow
- All Typescript code must pass [tslint](https://palantir.github.io/tslint/)

## Guidelines
- Use [create-react-app-typescript](https://github.com/wmonk/create-react-app-typescript) and `Eject` the build scripts so they can be tweaked by hand and we can modify `babel`, etc...
- Each module's files should be in a module specific folder and the overall folder structure should be well organized
- Only use .js files when absolutely required a used framework - Typescript everywhere else
- Please use `yarn` and not `npm`
- PRs for this issue will be code reviewed and will only be accepted if all of the requirements outlined here are satisfied   
- Use `flexbox` layout for all react-native views and ui widgets

## Developer Requirements
- You must be an experienced Typescript and node.js developer with some experience with one or more of these frameworks: `react`, `redux`, `react-native`, `react-native-web`, `react router`.

## Issue checklist
- [x] All required functionality implemented
- [ ] Demo app running on iOS device
- [ ] Demo app running on Android device
- [ ] Demo app running in web browser
- [ ] Demo app running in an Electron app
- [ ] Demo app navigation and use case works on all platforms
- [ ] Build, test and run docs in readme.md
- [ ] Well organized project folder structure that corresponds to the architecture
- [ ] All methods, types, interfaces and modules are well comment documented
- [ ] Typescript is used when possible instead of Javascript
- [ ] Yarn build, test and run scripts work for all platforms
- [ ] Full unit tests
- [ ] Demo app tests for each supported platform
- [ ] All Views and UI widgets are layed-out using flexbox.
- [ ] Your name added to authors

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 6.0 ETH (2810.25 USD @ $468.37/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/spacemeshos/cosmic/2/733).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $21,366.12 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 4 weeks, 1 day from now. Please review their questions below:


1. [iamonuwa](https://gitcoin.co/profile/iamonuwa) has started work. 	
 * Q: The task will be fun to work on. Am starting immediately and will post my progress as I go

**Comment by avive** [comment]
Thinking about starting to work on this issue?  Please chat with us here https://gitter.im/spacemesh-os/cosmic

**Comment by iamonuwa** [comment]
@avive this task is cool, am joining the gitter immediately

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Cancelled** 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 3 weeks, 5 days from now. Please review their questions below:


1. [iamonuwa](https://gitcoin.co/profile/iamonuwa) has started work. 	
 * Q: The task will be fun to work on. Am starting immediately and will post my progress as I go

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Cancelled** 

<hr>

__The funding of 6.0 ETH (2638.47 USD @ $439.75/ETH) attached to this issue has been **cancelled** by the bounty submitter__

 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $16,001.96 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 7 months ago.
Please review their action plans below:


**1) [samparsky](https://gitcoin.co/profile/samparsky) has been approved to start work.**

Provide proper testing and implementation

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/spacemeshos/cosmic/2/755).

**Comment by avive** [comment]
I think that this is the current status:

- [+] All required functionality implemented
- [+] Demo app running on iOS device
- [ ] Demo app running on Android device
- [+]  Demo app running in web browser
- [+] Demo app running in an Electron app
- [+] Demo app navigation and use case works on all platforms
- [ ]  Build, test and run docs in readme.md
- [ ]  Well organized project folder structure that corresponds to the architecture
- [ ] All methods, types, interfaces and modules are well comment documented
- [+] Typescript is used when possible instead of Javascript
- [+] Yarn build, test and run scripts work for all platforms
- [ ] Full unit tests
- [ ] Demo app tests for each supported platform
- [ ] All Views and UI widgets are layed-out using flexbox.
- [ ] Your name added to authors

**Comment by iamonuwa** [comment]
At the moment, 
[x] Full unit tests
[x] Build, test, and run docs in readme.md,
[x] Demo app running on Android device

**Comment by avive** [comment]
Looks like we are getting close.. updated the checklist above.

**Comment by vikaskyadav** [comment]
Let me know where can I collaborate and contribute.

**Comment by avive** [comment]
@vikaskyadav You can work on this issue to familiarize yourself with the codebase  https://github.com/spacemeshos/cosmic/issues/7 - we are going to have additional funded issues soon as well.

**Comment by vikaskyadav** [comment]
sounds good!

**Comment by gitcoinbot** [comment]
⚡️ A tip worth 3.00000  ETH (1079.03 USD @ $359.68/ETH) has been granted to @iamonuwa for this issue from @avive. ⚡️ 

Nice work @iamonuwa! Your tip has automatically been deposited in the ETH address we have on file.

 * $23752.64 in Funded OSS Work Available at: https://gitcoin.co/explorer
 * Incentivize contributions to your repo: <a href='https://gitcoin.co/tip'>Send a Tip</a> or <a href='https://gitcoin.co/funding/new'>Fund a PR</a>
 * No Email? Get help on the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>

**Comment by gitcoinbot** [comment]
⚡️ A tip worth 3.00000  ETH (1079.03 USD @ $359.68/ETH) has been granted to @samparsky for this issue from @avive. ⚡️ 

Nice work @samparsky! To redeem your tip, login to Gitcoin at https://gitcoin.co/explorer and select 'Claim Tip' from dropdown menu in the top right, or check your email for a link to the tip redemption page. 

 * $23752.64 in Funded OSS Work Available at: https://gitcoin.co/explorer
 * Incentivize contributions to your repo: <a href='https://gitcoin.co/tip'>Send a Tip</a> or <a href='https://gitcoin.co/funding/new'>Fund a PR</a>
 * No Email? Get help on the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>

**Comment by gitcoinbot** [comment]
⚡️ A tip worth 3.00000  ETH (1027.81 USD @ $342.6/ETH) has been granted to @samparsky for this issue from @avive. ⚡️ 

Nice work @samparsky! To redeem your tip, login to Gitcoin at https://gitcoin.co/explorer and select 'Claim Tip' from dropdown menu in the top right, or check your email for a link to the tip redemption page. 

 * $25188.25 in Funded OSS Work Available at: https://gitcoin.co/explorer
 * Incentivize contributions to your repo: <a href='https://gitcoin.co/tip'>Send a Tip</a> or <a href='https://gitcoin.co/funding/new'>Fund a PR</a>
 * No Email? Get help on the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>

**Comment by gitcoinbot** [comment]
⚡️ A tip worth 3.00000  ETH (1027.81 USD @ $342.6/ETH) has been granted to @iamonuwa for this issue from @avive. ⚡️ 

Nice work @iamonuwa! Your tip has automatically been deposited in the ETH address we have on file.

 * $25188.25 in Funded OSS Work Available at: https://gitcoin.co/explorer
 * Incentivize contributions to your repo: <a href='https://gitcoin.co/tip'>Send a Tip</a> or <a href='https://gitcoin.co/funding/new'>Fund a PR</a>
 * No Email? Get help on the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>

**Comment by gitcoinbot** [comment]
⚡️ A tip worth 3.00000  ETH (789.12 USD @ $263.04/ETH) has been granted to @iamonuwa for this issue from @avive. ⚡️ 

Nice work @iamonuwa! Your tip has automatically been deposited in the ETH address we have on file.

 * $19861.28 in Funded OSS Work Available at: https://gitcoin.co/explorer
 * Incentivize contributions to your repo: <a href='https://gitcoin.co/tip'>Send a Tip</a> or <a href='https://gitcoin.co/funding/new'>Fund a PR</a>
 * No Email? Get help on the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>

**Comment by gitcoinbot** [comment]
⚡️ A tip worth 3.00000  ETH (789.12 USD @ $263.04/ETH) has been granted to @samparsky for this issue from @avive. ⚡️ 

Nice work @samparsky! Your tip has automatically been deposited in the ETH address we have on file.

 * $19861.28 in Funded OSS Work Available at: https://gitcoin.co/explorer
 * Incentivize contributions to your repo: <a href='https://gitcoin.co/tip'>Send a Tip</a> or <a href='https://gitcoin.co/funding/new'>Fund a PR</a>
 * No Email? Get help on the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__The funding of 6.0 ETH (1578.25 USD @ $263.04/ETH) (plus a crowdfund of 0.1 ETH worth $41.74) attached to this issue has been approved & issued.__  

 * Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/spacemeshos/cosmic/2/755)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $18,283.03 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
